services:
  mock-server:
    image: wiremock/wiremock:3.5.4
    container_name: mock-server
    volumes:
      - ./wiremock:/home/wiremock
    ports:
      - "8000:8080"
  payment-db:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db